apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fb0b1u24c-java-springboot 
  janus-idp.io/tekton: fb0b1u24c-java-springboot
  backstage.io/kubernetes-id: fb0b1u24c-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fb0b1u24c-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  